### ISSUE TITLE
Feature suggestion: Add editable number of currently enrolled players

### ISSUE THREAD

**Issue by watermelonwolverine** [bitfl0wer/magicaltavern#33]
It would be nice to let the players know how many are enrolled in a campaign.

Example:

# Aktuell eingeschrieben
4/6 Spieler:innen
# Minimal Anzahl der Spieler erreicht
Ja
___
Edit manually with something like:

`/setplayercount <msg-id> <player-count>`
`/setplayercount 23451341253212353 4`

**Comment by bitfl0wer** [comment]
This will be integrated into #15. Thanks for the Issue!
